spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

service:
  membership:
    url: http://localhost:8081

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: user
#    password:
#    ddl-auto: create-drop